### PR TITLE
update terminology in README

### LINKED ISSUE #44: Domain language: Pub/Sub vs Producer/Consumer
We should lock down terminology for consistency of terms in codebase.

Do we use:
Publisher / Subscriber

or

Producer / Consumer

or

something else?

### PR DESCRIPTION
**Pull request by harbu**
Define terms client, publisher, subscriber, and also broker and stream.

fixes #44, #45

### CODE REVIEW

**Review by ptesavol — CHANGES_REQUESTED** [review]
I would say "A _tracker_ assists nodes to discover other nodes. Peers can act as trackers but a tracker might also be a centralised server in some configurations".

In the two last lines I would replace word "node" with "broker".

How about also adding definition of _leader_?

**Comment by harbu** [comment]
I replaced word _node_ with _broker_ in the definitions of _publisher_ and _subscriber_. With regards to the wording of _tracker_, does the statement "Peers can act as trackers but a tracker might also be a centralised server in some configurations" apply in our case?

**Comment by ptesavol** [comment]
I think in some private, commercial setups (such as the smart city case) a centralised tracker may be relevant.

**Comment by harbu** [comment]
Fair enough, updated definition.

**Review by mirpo — APPROVED** [review]
what about code? should we rename all classes after that?

**Comment by harbu** [comment]
If time allows, I think we should make a pass through the code to make sure stuff is named appropriately. But most of all, we should make sure to use follow these terms in future code we write.

**Comment by harbu** [comment]
Whoops accidentally closed, re-opened...

**Review by ptesavol — APPROVED** [review]

**Pull request merged**
